# Generated by Django 4.2 on 2023-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokok_id', models.PositiveBigIntegerField()),
                ('pokok_name', models.CharField(max_length=100)),
                ('grow_date', models.DateField()),
                ('height_date', models.FloatField()),
                ('leaf_colour', models.CharField(max_length=50)),
            ],
        ),
    ]
